-- Additive only. Never DROP or rewrite existing rows.
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "labelConfig" JSONB;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "locationConfig" JSONB;
ALTER TABLE "Settings" ADD COLUMN IF NOT EXISTS "kotConfig" JSONB;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'completed';
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "cancelReason" TEXT;
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "cancelledAt" TIMESTAMP(3);
ALTER TABLE "Sale" ADD COLUMN IF NOT EXISTS "cancelledByName" TEXT;
ALTER TABLE "KOTOrder" ADD COLUMN IF NOT EXISTS "cancelledAt" TIMESTAMP(3);
ALTER TABLE "KOTOrder" ADD COLUMN IF NOT EXISTS "cancelReason" TEXT;
ALTER TABLE "KOTOrder" ADD COLUMN IF NOT EXISTS "cancelledByName" TEXT;
ALTER TABLE "KOTOrderItem" ADD COLUMN IF NOT EXISTS "kotBatchNumber" INTEGER;
