export const QUERY_KEYS = {
  PRODUCTS: 'products',
  CATEGORIES: 'categories',
  SUPPLIERS: 'suppliers',
  CUSTOMERS: 'customers',
  SALES: 'sales',
  PURCHASES: 'purchases',
  EXPENSES: 'expenses',
  CREDITS: 'credits',
  REPORTS_DASHBOARD: 'reports-dashboard',
  REPORTS_SALES: 'reports-sales',
  REPORTS_PL: 'reports-pl',
  REPORTS_TAX: 'reports-tax',
  REPORTS_PAYMENT_MODES: 'reports-payment-modes',
  REPORTS_PROFIT_BREAKDOWN: 'reports-profit-breakdown',
  REPORTS_TOP_PRODUCTS: 'reports-top-products',
  REPORTS_TOP_CATEGORIES: 'reports-top-categories',
  REPORTS_EXPENSE_SUMMARY: 'reports-expense-summary',
  SETTINGS: 'settings',
  TOKEN_TYPES: 'token-types',
  TOKENS: 'tokens',
  LOCATIONS: 'locations',
  LOCATION_STOCK: 'location-stock',
  STOCK_TRANSFERS: 'stock-transfers',
  RESTAURANT_TABLES: 'restaurant-tables',
  KOT_ORDERS: 'kot-orders',
} as const
