export const ROUTES = {
  LANDING: '/',
  LOGIN: '/login',
  ACCESS_SELECTION: '/access-selection',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  POS: '/pos',
  POS_LITE: '/pos-lite',
  TOKENS: '/tokens',
  UTILITY_KIOSK: '/utility-kiosk',
  PRODUCTS: '/products',
  CATEGORIES: '/categories',
  CUSTOMERS: '/customers',
  CUSTOMER_DETAIL: (id: string) => `/customers/${id}`,
  SUPPLIERS: '/suppliers',
  SUPPLIER_DETAIL: (id: string) => `/suppliers/${id}`,
  SALES: '/sales',
  SALE_DETAIL: (id: string) => `/sales/${id}`,
  PURCHASES: '/purchases',
  EXPENSES: '/expenses',
  CREDITS: '/credits',
  DAYBOOK: '/daybook',
  REPORTS: '/reports',
  REPORTS_SALES: '/reports/sales',
  REPORTS_PL: '/reports/profit-loss',
  REPORTS_TAX: '/reports/tax',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  PRINTERS: '/printers',
  PRINT_JOBS: '/print-jobs',
  LOCATIONS: '/locations',
  KOT: '/kot',
  KOT_KDS: '/kot/kds',
  KITCHEN_INVENTORY: '/kitchen-inventory',
  PUBLIC_RECEIPT: '/receipt/:id',
  PUBLIC_BILL: '/bill/:id',
  PUBLIC_INVOICE: '/invoice/:id',
  FEEDBACK: '/settings',
} as const
