export const ROUTES = {
  LOGIN: '/login',
  ACCESS_SELECTION: '/access-selection',
  ONBOARDING: '/onboarding',
  DASHBOARD: '/dashboard',
  POS: '/pos',
  POS_LITE: '/pos-lite',
  PRODUCTS: '/products',
  CATEGORIES: '/categories',
  CUSTOMERS: '/customers',
  CUSTOMER_DETAIL: (id: string) => `/customers/${id}`,
  SUPPLIERS: '/suppliers',
  SALES: '/sales',
  SALE_DETAIL: (id: string) => `/sales/${id}`,
  PURCHASES: '/purchases',
  EXPENSES: '/expenses',
  CREDITS: '/credits',
  REPORTS: '/reports',
  REPORTS_SALES: '/reports/sales',
  REPORTS_PL: '/reports/profit-loss',
  REPORTS_TAX: '/reports/tax',
  SETTINGS: '/settings',
} as const
