import type { A4InvoiceTemplateId, PrinterConfig } from '@/types/settings.types'
import type { Sale } from '@/types/sale.types'

export type A4InvoiceTheme = PrinterConfig['invoiceColorTheme']
export type A4InvoiceLayout =
  | 'classic'
  | 'banded'
  | 'folio'
  | 'compact'
  | 'statement'
  | 'ticket'
  | 'clinical'
  | 'industrial'

export interface A4SampleItem {
  productName: string
  quantity: number
  sellingPrice: number
  taxRate: number
  sku?: string
  unit?: string
}

export interface A4InvoiceTemplate {
  id: A4InvoiceTemplateId
  name: string
  category: string
  description: string
  layout: A4InvoiceLayout
  theme: A4InvoiceTheme
  docTitle: string
  defaultTerms: string
  codeLabel: 'HSN' | 'SAC' | 'HSN/SAC'
  unitLabel: string
  showHsn: boolean
  showSku: boolean
  showUnit: boolean
  showBatchExpiry: boolean
  showFssai: boolean
  showLicense: boolean
  showBank: boolean
  meta1Label: string
  meta2Label: string
  meta3Label: string
  meta3Value: string
  sampleItems: A4SampleItem[]
}

export const A4_INVOICE_TEMPLATES: A4InvoiceTemplate[] = [
  {
    id: 'retail',
    name: 'Retail / Kirana',
    category: 'Shop',
    description: 'GST tax invoice with qty, rate, HSN and tax split for counter sales.',
    layout: 'classic',
    theme: 'navy',
    docTitle: 'TAX INVOICE',
    defaultTerms: '1. Goods once sold will not be taken back or exchanged.\n2. All disputes are subject to local jurisdiction only.\n3. E. & O.E.',
    codeLabel: 'HSN',
    unitLabel: 'pcs',
    showHsn: true,
    showSku: false,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: false,
    showLicense: false,
    showBank: true,
    meta1Label: 'Place of supply',
    meta2Label: 'Reverse charge',
    meta3Label: '',
    meta3Value: '',
    sampleItems: [
      { productName: 'Sunflower Oil 1L', quantity: 2, sellingPrice: 165, taxRate: 5, sku: 'OIL-1L', unit: 'pcs' },
      { productName: 'Atta 5 kg', quantity: 1, sellingPrice: 280, taxRate: 5, sku: 'ATTA-5', unit: 'pcs' },
      { productName: 'Detergent Powder 1 kg', quantity: 1, sellingPrice: 145, taxRate: 18, sku: 'DET-1', unit: 'pcs' },
    ],
  },
  {
    id: 'grocery',
    name: 'Grocery / Supermarket',
    category: 'Shop',
    description: 'Dense supermarket layout with HSN, unit and packed-goods columns.',
    layout: 'compact',
    theme: 'emerald',
    docTitle: 'TAX INVOICE',
    defaultTerms: '1. Packed goods are sold as per MRP / declared weight.\n2. Perishable items cannot be returned.\n3. Please check items before leaving the store.',
    codeLabel: 'HSN',
    unitLabel: 'pcs',
    showHsn: true,
    showSku: true,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: true,
    showLicense: false,
    showBank: false,
    meta1Label: 'Bill type',
    meta2Label: 'Counter',
    meta3Label: '',
    meta3Value: '',
    sampleItems: [
      { productName: 'Basmati Rice 5 kg', quantity: 1, sellingPrice: 520, taxRate: 5, sku: 'RICE-5', unit: 'pkt' },
      { productName: 'Fresh Tomato', quantity: 1.5, sellingPrice: 40, taxRate: 0, sku: 'VEG-TOM', unit: 'kg' },
      { productName: 'Amul Butter 100g', quantity: 2, sellingPrice: 58, taxRate: 12, sku: 'BUT-100', unit: 'pcs' },
    ],
  },
  {
    id: 'cafe',
    name: 'Cafe',
    category: 'F&B',
    description: 'F&B invoice with table, covers, FSSAI and service notes.',
    layout: 'banded',
    theme: 'amber',
    docTitle: 'TAX INVOICE',
    defaultTerms: '1. Service charge, if any, is shown separately.\n2. Packed food once sold cannot be returned.\n3. FSSAI licence number is printed above.',
    codeLabel: 'SAC',
    unitLabel: 'qty',
    showHsn: true,
    showSku: false,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: true,
    showLicense: false,
    showBank: false,
    meta1Label: 'Table',
    meta2Label: 'Covers',
    meta3Label: 'SAC',
    meta3Value: '996331',
    sampleItems: [
      { productName: 'Cappuccino', quantity: 2, sellingPrice: 180, taxRate: 5, unit: 'cup' },
      { productName: 'Veg Sandwich', quantity: 1, sellingPrice: 160, taxRate: 5, unit: 'plt' },
      { productName: 'Chocolate Brownie', quantity: 1, sellingPrice: 140, taxRate: 5, unit: 'pcs' },
    ],
  },
  {
    id: 'restaurant',
    name: 'Restaurant',
    category: 'F&B',
    description: 'Dine-in tax invoice with table, covers and kitchen item names.',
    layout: 'ticket',
    theme: 'wine',
    docTitle: 'TAX INVOICE',
    defaultTerms: '1. Restaurant GST on food & beverage as applicable.\n2. Tips are voluntary and not part of this invoice.\n3. All disputes subject to local jurisdiction.',
    codeLabel: 'SAC',
    unitLabel: 'qty',
    showHsn: true,
    showSku: false,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: true,
    showLicense: false,
    showBank: false,
    meta1Label: 'Table',
    meta2Label: 'Covers',
    meta3Label: 'Waiter',
    meta3Value: '',
    sampleItems: [
      { productName: 'Butter Chicken', quantity: 1, sellingPrice: 420, taxRate: 5, unit: 'plt' },
      { productName: 'Garlic Naan', quantity: 4, sellingPrice: 55, taxRate: 5, unit: 'pcs' },
      { productName: 'Sweet Lassi', quantity: 2, sellingPrice: 90, taxRate: 5, unit: 'gls' },
    ],
  },
  {
    id: 'hotel',
    name: 'Hotel / Lodging',
    category: 'Hospitality',
    description: 'Guest folio with room, check-in / check-out and occupancy charges.',
    layout: 'folio',
    theme: 'navy',
    docTitle: 'GUEST FOLIO / TAX INVOICE',
    defaultTerms: '1. Check-out time as per hotel policy.\n2. Room tariff is exclusive of extra occupancy unless stated.\n3. Guest signature acknowledges the charges above.',
    codeLabel: 'SAC',
    unitLabel: 'nights',
    showHsn: true,
    showSku: false,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: false,
    showLicense: true,
    showBank: true,
    meta1Label: 'Room no.',
    meta2Label: 'Check-in',
    meta3Label: 'Check-out',
    meta3Value: '',
    sampleItems: [
      { productName: 'Deluxe Room — Double Occupancy', quantity: 2, sellingPrice: 3500, taxRate: 12, unit: 'night' },
      { productName: 'Breakfast (MAP)', quantity: 2, sellingPrice: 450, taxRate: 5, unit: 'cover' },
      { productName: 'Laundry', quantity: 1, sellingPrice: 280, taxRate: 18, unit: 'job' },
    ],
  },
  {
    id: 'qsr',
    name: 'QSR / Takeaway',
    category: 'F&B',
    description: 'Quick-service bill with order number and packed-item list.',
    layout: 'compact',
    theme: 'amber',
    docTitle: 'TAX INVOICE',
    defaultTerms: '1. Please check your order at the counter.\n2. Packed items cannot be exchanged once sealed.\n3. GST as applicable on restaurant service.',
    codeLabel: 'SAC',
    unitLabel: 'qty',
    showHsn: false,
    showSku: false,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: true,
    showLicense: false,
    showBank: false,
    meta1Label: 'Order no.',
    meta2Label: 'Type',
    meta3Label: 'Token',
    meta3Value: '',
    sampleItems: [
      { productName: 'Veg Burger Combo', quantity: 2, sellingPrice: 199, taxRate: 5, unit: 'box' },
      { productName: 'French Fries', quantity: 1, sellingPrice: 89, taxRate: 5, unit: 'pkt' },
      { productName: 'Cold Coffee', quantity: 2, sellingPrice: 129, taxRate: 5, unit: 'cup' },
    ],
  },
  {
    id: 'electrician',
    name: 'Electrician / Electrical',
    category: 'Trades',
    description: 'Work-order invoice with job no., site address, labour vs material and SAC 9954.',
    layout: 'statement',
    theme: 'slate',
    docTitle: 'TAX INVOICE — WORK ORDER',
    defaultTerms: '1. Warranty on workmanship: 90 days unless stated otherwise.\n2. Materials remain our property until paid in full.\n3. Extra visits / extra wiring billed separately.\n4. SAC 995461 — electrical installation services.',
    codeLabel: 'SAC',
    unitLabel: 'job',
    showHsn: true,
    showSku: false,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: false,
    showLicense: true,
    showBank: true,
    meta1Label: 'Job / work order no.',
    meta2Label: 'Site / installation address',
    meta3Label: 'SAC',
    meta3Value: '995461',
    sampleItems: [
      { productName: 'Wiring labour — 2BHK flat', quantity: 1, sellingPrice: 8500, taxRate: 18, unit: 'job' },
      { productName: 'MCB 32A + DB board', quantity: 1, sellingPrice: 2200, taxRate: 18, unit: 'set' },
      { productName: '1.5 sq mm copper wire (90 m)', quantity: 2, sellingPrice: 1850, taxRate: 18, unit: 'coil' },
    ],
  },
  {
    id: 'cosmetics',
    name: 'Cosmetics / Salon',
    category: 'Beauty',
    description: 'Beauty invoice for retail products and salon services, with batch / shade notes.',
    layout: 'clinical',
    theme: 'rose',
    docTitle: 'TAX INVOICE',
    defaultTerms: '1. Opened cosmetics cannot be returned.\n2. Salon services are non-refundable once completed.\n3. Patch test recommended before colour / chemical treatments.',
    codeLabel: 'HSN/SAC',
    unitLabel: 'qty',
    showHsn: true,
    showSku: true,
    showUnit: true,
    showBatchExpiry: true,
    showFssai: false,
    showLicense: true,
    showBank: false,
    meta1Label: 'Stylist / therapist',
    meta2Label: 'Service type',
    meta3Label: 'Batch / shade',
    meta3Value: '',
    sampleItems: [
      { productName: 'Hair Colour — Global', quantity: 1, sellingPrice: 1800, taxRate: 18, sku: 'SVC-CLR', unit: 'svc' },
      { productName: 'Face Serum 30ml', quantity: 1, sellingPrice: 899, taxRate: 18, sku: 'SER-30', unit: 'btl' },
      { productName: 'Keratin Treatment', quantity: 1, sellingPrice: 3500, taxRate: 18, sku: 'SVC-KER', unit: 'svc' },
    ],
  },
  {
    id: 'pharmacy',
    name: 'Pharmacy',
    category: 'Health',
    description: 'Medical bill with batch, expiry and composition-style item lines.',
    layout: 'clinical',
    theme: 'teal',
    docTitle: 'TAX INVOICE / CASH MEMO',
    defaultTerms: '1. Medicines once sold cannot be taken back.\n2. Store in a cool, dry place as directed.\n3. Schedule H / H1 drugs dispensed against prescription only.',
    codeLabel: 'HSN',
    unitLabel: 'qty',
    showHsn: true,
    showSku: true,
    showUnit: true,
    showBatchExpiry: true,
    showFssai: false,
    showLicense: true,
    showBank: false,
    meta1Label: 'Doctor / Rx no.',
    meta2Label: 'Patient',
    meta3Label: 'Drug licence',
    meta3Value: '',
    sampleItems: [
      { productName: 'Paracetamol 650 mg (10 tab)', quantity: 2, sellingPrice: 28, taxRate: 12, sku: 'PCM-650', unit: 'str' },
      { productName: 'Cough Syrup 100ml', quantity: 1, sellingPrice: 95, taxRate: 12, sku: 'SYR-100', unit: 'btl' },
      { productName: 'Vitamin D3 60k', quantity: 1, sellingPrice: 145, taxRate: 12, sku: 'VD3-60', unit: 'cap' },
    ],
  },
  {
    id: 'bakery',
    name: 'Bakery',
    category: 'F&B',
    description: 'Bakery invoice for packed and fresh items with FSSAI on the header.',
    layout: 'banded',
    theme: 'amber',
    docTitle: 'TAX INVOICE',
    defaultTerms: '1. Fresh bakery items cannot be returned.\n2. Best before date is printed on packed goods.\n3. Custom cakes require 50% advance.',
    codeLabel: 'HSN',
    unitLabel: 'pcs',
    showHsn: true,
    showSku: false,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: true,
    showLicense: false,
    showBank: false,
    meta1Label: 'Order for',
    meta2Label: 'Pickup date',
    meta3Label: '',
    meta3Value: '',
    sampleItems: [
      { productName: 'Chocolate Truffle Cake 1 kg', quantity: 1, sellingPrice: 850, taxRate: 5, unit: 'kg' },
      { productName: 'Butter Croissant', quantity: 6, sellingPrice: 55, taxRate: 5, unit: 'pcs' },
      { productName: 'Bread Loaf 400g', quantity: 2, sellingPrice: 45, taxRate: 5, unit: 'pcs' },
    ],
  },
  {
    id: 'clothing',
    name: 'Apparel / Boutique',
    category: 'Fashion',
    description: 'Fashion invoice with SKU, size and garment description.',
    layout: 'classic',
    theme: 'royal',
    docTitle: 'TAX INVOICE',
    defaultTerms: '1. Exchange within 7 days with tags and invoice. No cash refund.\n2. Altered / worn garments cannot be exchanged.\n3. Colour and texture may vary slightly from display.',
    codeLabel: 'HSN',
    unitLabel: 'pcs',
    showHsn: true,
    showSku: true,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: false,
    showLicense: false,
    showBank: true,
    meta1Label: 'Season / collection',
    meta2Label: 'Size / colour',
    meta3Label: '',
    meta3Value: '',
    sampleItems: [
      { productName: 'Cotton Kurta — Size M', quantity: 1, sellingPrice: 1299, taxRate: 5, sku: 'KUR-M-21', unit: 'pcs' },
      { productName: 'Chiffon Dupatta', quantity: 1, sellingPrice: 499, taxRate: 5, sku: 'DUP-CH', unit: 'pcs' },
      { productName: 'Palazzo Pants — Size 28', quantity: 1, sellingPrice: 899, taxRate: 5, sku: 'PAL-28', unit: 'pcs' },
    ],
  },
  {
    id: 'electronics',
    name: 'Electronics / Mobiles',
    category: 'Retail',
    description: 'Serial / IMEI style invoice with warranty note and SKU.',
    layout: 'industrial',
    theme: 'slate',
    docTitle: 'TAX INVOICE',
    defaultTerms: '1. Manufacturer warranty as per brand T&C. Invoice required for claims.\n2. Physical / liquid damage is not covered.\n3. Serial / IMEI must match the sealed box.\n4. Goods once sold are not returnable except manufacturing defect within 7 days.',
    codeLabel: 'HSN',
    unitLabel: 'pcs',
    showHsn: true,
    showSku: true,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: false,
    showLicense: false,
    showBank: true,
    meta1Label: 'Serial / IMEI',
    meta2Label: 'Warranty',
    meta3Label: '',
    meta3Value: '12 months brand',
    sampleItems: [
      { productName: 'Smartphone 128 GB', quantity: 1, sellingPrice: 14999, taxRate: 18, sku: 'PHN-128', unit: 'pcs' },
      { productName: 'Tempered Glass', quantity: 1, sellingPrice: 299, taxRate: 18, sku: 'TG-6', unit: 'pcs' },
      { productName: '20W Fast Charger', quantity: 1, sellingPrice: 799, taxRate: 18, sku: 'CHG-20', unit: 'pcs' },
    ],
  },
  {
    id: 'hardware',
    name: 'Hardware / Building',
    category: 'Trades',
    description: 'Building-material invoice with unit (kg / m / bag) and HSN.',
    layout: 'industrial',
    theme: 'amber',
    docTitle: 'TAX INVOICE',
    defaultTerms: '1. Material once cut / mixed cannot be returned.\n2. Unloading at site is extra unless quoted.\n3. Shortage must be reported at the time of delivery.',
    codeLabel: 'HSN',
    unitLabel: 'unit',
    showHsn: true,
    showSku: true,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: false,
    showLicense: false,
    showBank: true,
    meta1Label: 'Site / delivery',
    meta2Label: 'PO / reference',
    meta3Label: '',
    meta3Value: '',
    sampleItems: [
      { productName: 'OPC Cement 50 kg', quantity: 20, sellingPrice: 380, taxRate: 28, sku: 'CEM-50', unit: 'bag' },
      { productName: 'TMT Bar 12 mm', quantity: 50, sellingPrice: 62, taxRate: 18, sku: 'TMT-12', unit: 'kg' },
      { productName: 'White Primer 20 L', quantity: 2, sellingPrice: 1850, taxRate: 18, sku: 'PRI-20', unit: 'tin' },
    ],
  },
  {
    id: 'services',
    name: 'Professional services',
    category: 'Services',
    description: 'SAC-based professional invoice for consulting, repair or studio work.',
    layout: 'statement',
    theme: 'navy',
    docTitle: 'TAX INVOICE',
    defaultTerms: '1. Payment due on receipt unless credit terms are agreed in writing.\n2. Reverse charge: as marked on this invoice.\n3. This is a tax invoice under GST for supply of services.',
    codeLabel: 'SAC',
    unitLabel: 'hrs',
    showHsn: true,
    showSku: false,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: false,
    showLicense: false,
    showBank: true,
    meta1Label: 'Engagement / job',
    meta2Label: 'Period',
    meta3Label: 'SAC',
    meta3Value: '9983',
    sampleItems: [
      { productName: 'On-site consultation', quantity: 4, sellingPrice: 1500, taxRate: 18, unit: 'hr' },
      { productName: 'Report / documentation', quantity: 1, sellingPrice: 2500, taxRate: 18, unit: 'job' },
    ],
  },
  {
    id: 'wholesale',
    name: 'Wholesale / B2B',
    category: 'Trade',
    description: 'B2B GST invoice with buyer GSTIN, place of supply and HSN.',
    layout: 'classic',
    theme: 'navy',
    docTitle: 'TAX INVOICE',
    defaultTerms: '1. Payment as per agreed credit days. Interest on overdue bills as per agreement.\n2. Buyer to claim ITC only if this invoice is reported in GSTR-1.\n3. Place of supply as stated. Reverse charge: as marked.',
    codeLabel: 'HSN',
    unitLabel: 'pcs',
    showHsn: true,
    showSku: true,
    showUnit: true,
    showBatchExpiry: false,
    showFssai: false,
    showLicense: false,
    showBank: true,
    meta1Label: 'Buyer GSTIN',
    meta2Label: 'Place of supply',
    meta3Label: 'PO no.',
    meta3Value: '',
    sampleItems: [
      { productName: 'LED Bulb 9W (box of 20)', quantity: 10, sellingPrice: 860, taxRate: 18, sku: 'LED-9-20', unit: 'box' },
      { productName: 'Extension Board 4-way', quantity: 24, sellingPrice: 185, taxRate: 18, sku: 'EXT-4', unit: 'pcs' },
      { productName: 'PVC Tape roll', quantity: 50, sellingPrice: 18, taxRate: 18, sku: 'TAP-PVC', unit: 'pcs' },
    ],
  },
]

export const getA4InvoiceTemplate = (id?: string | null): A4InvoiceTemplate =>
  A4_INVOICE_TEMPLATES.find(t => t.id === id) || A4_INVOICE_TEMPLATES[0]

export const applyA4TemplateDefaults = (
  prev: PrinterConfig,
  id: A4InvoiceTemplateId,
): PrinterConfig => {
  const t = getA4InvoiceTemplate(id)
  return {
    ...prev,
    invoiceTemplateId: id,
    invoiceColorTheme: t.theme,
    invoiceDocTitle: t.docTitle,
    invoiceTermsText: t.defaultTerms,
    invoiceShowHsn: t.showHsn,
    invoiceShowSku: t.showSku,
    invoiceShowUnit: t.showUnit,
    invoiceShowBatchExpiry: t.showBatchExpiry,
    invoiceMeta1Label: t.meta1Label,
    invoiceMeta1Value: id === 'qsr' ? 'Takeaway' : id === 'wholesale' ? '' : prev.invoiceMeta1Value || '',
    invoiceMeta2Label: t.meta2Label,
    invoiceMeta2Value: id === 'qsr' ? 'Takeaway' : t.meta2Label.toLowerCase().includes('reverse') ? 'No' : '',
    invoiceMeta3Label: t.meta3Label,
    invoiceMeta3Value: t.meta3Value,
    invoiceReverseCharge: 'No',
    invoiceSignatureName: prev.invoiceSignatureName || 'Authorised Signatory',
  }
}

export const sampleSaleForTemplate = (id?: A4InvoiceTemplateId | string | null): Sale => {
  const t = getA4InvoiceTemplate(id)
  const items = t.sampleItems.map((item, i) => {
    const line = item.sellingPrice * item.quantity
    const taxAmount = Math.round(line * (item.taxRate / 100) * 100) / 100
    return {
      productId: `sample-${t.id}-${i}`,
      productName: item.productName,
      quantity: item.quantity,
      sellingPrice: item.sellingPrice,
      discount: 0,
      taxRate: item.taxRate,
      taxAmount,
      total: line + taxAmount,
    }
  })
  const subtotal = items.reduce((s, it) => s + it.sellingPrice * it.quantity, 0)
  const totalTax = items.reduce((s, it) => s + it.taxAmount, 0)
  return {
    id: `preview-${t.id}`,
    invoiceNumber: 'INV-2026-0089',
    items,
    subtotal,
    totalDiscount: 0,
    totalTax,
    grandTotal: subtotal + totalTax,
    paymentMethod: 'cash',
    amountPaid: subtotal + totalTax,
    changeReturned: 0,
    isQuickBill: false,
    createdAt: new Date().toISOString(),
  }
}
