import type { LucideIcon } from 'lucide-react-native';
import {
  Store,
  Croissant,
  Coffee,
  UtensilsCrossed,
  Utensils,
  Receipt,
  ShoppingBag,
  Wine,
  ChefHat,
  BedDouble,
  ShoppingCart,
  Shirt,
  Footprints,
  Cpu,
  Smartphone,
  Pill,
  Scissors,
  Hammer,
  Car,
  Gem,
  Sofa,
  BookOpen,
  Pizza,
  IceCream,
  CupSoda,
  Apple,
  Fish,
  Glasses,
  Gift,
  Sparkles,
  Wrench,
  Droplets,
  Microscope,
  Dumbbell,
  Boxes,
  Truck,
  Flame,
} from 'lucide-react-native';

export type TemplateCategory =
  | 'all'
  | 'custom'
  | 'food'
  | 'restaurant'
  | 'retail'
  | 'fashion'
  | 'tech'
  | 'services'
  | 'health'
  | 'b2b';

export interface TemplateSampleItem {
  productName: string;
  quantity: number;
  unitPrice: number;
  total: number;
  unit?: string;
}

/** Restaurant thermal layouts used by PrinterService + ReceiptTemplateMockup. */
export type RestaurantLayout =
  | 'restaurant_bill'
  | 'restaurant_compact'
  | 'restaurant_gst'
  | 'restaurant_takeaway'
  | 'restaurant_roomservice';

export type ReceiptLayout = 'standard' | RestaurantLayout;

export function isRestaurantLayout(layout?: ReceiptLayout | null): layout is RestaurantLayout {
  return (
    layout === 'restaurant_bill' ||
    layout === 'restaurant_compact' ||
    layout === 'restaurant_gst' ||
    layout === 'restaurant_takeaway' ||
    layout === 'restaurant_roomservice'
  );
}

export interface ReceiptTemplate {
  id: string;
  name: string;
  category: TemplateCategory;
  keywords: string[];
  /** Lucide icon used in the Templates picker grid */
  icon: LucideIcon;
  /** Decorative glyph printed on the actual receipt header */
  emoji: string;
  /** Header icon-badge background in the HTML/System-Print preview */
  accentColor: string;
  /** Shown under the store name on the printed receipt header */
  tagline: string;
  /** Replaces the generic "Thank you for your purchase!" footer line */
  footerMessage: string;
  /** "Invoice No" / "Bill #" / "Order No" / "Token #" — vertical billing label */
  billLabel: string;
  /** Item table column headers */
  itemColumnLeft: string;
  itemColumnRight: string;
  /** Section header above the item list */
  itemLabel: string;
  /** Whether to print the Taxable Amt / SGST / CGST breakdown */
  showTaxBreakdown: boolean;
  /** Whether to print a "Customer:" line */
  showCustomerLine: boolean;
  /** Character used for the thin divider rule between sections */
  dividerChar: string;
  /** Optional alternate print layout (defaults to standard two-column receipt) */
  layout?: ReceiptLayout;
  /** Shown as a size chip on the template card (e.g. restaurant 48mm printable head). */
  paperFit?: '48mm' | '58mm' | '80mm';
  /** Demo header/meta used by the template gallery mockup and test prints. */
  previewStoreName?: string;
  previewAddress?: string;
  previewPhone?: string;
  previewGstin?: string;
  previewInvoice?: string;
  previewDate?: string;
  previewCustomerName?: string;
  previewCustomerPhone?: string;
  previewTableNo?: string;
  previewWaiter?: string;
  /** Realistic demo items tailored to this business vertical */
  sampleItems: TemplateSampleItem[];
}

export interface CategoryFilterOption {
  id: TemplateCategory;
  label: string;
  emoji: string;
}

export const TEMPLATE_CATEGORIES: CategoryFilterOption[] = [
  { id: 'all', label: 'All', emoji: '🌟' },
  { id: 'custom', label: 'Custom', emoji: '🛠️' },
  { id: 'food', label: 'Food & Dining', emoji: '🍔' },
  { id: 'restaurant', label: 'Restaurant & Cafe', emoji: '🍽️' },
  { id: 'retail', label: 'Retail & Grocery', emoji: '🛒' },
  { id: 'fashion', label: 'Fashion & Lifestyle', emoji: '👗' },
  { id: 'tech', label: 'Electronics & Tech', emoji: '📱' },
  { id: 'services', label: 'Services & Repair', emoji: '✂️' },
  { id: 'health', label: 'Health & Wellness', emoji: '💊' },
  { id: 'b2b', label: 'Wholesale & B2B', emoji: '📦' },
];

export const RECEIPT_TEMPLATES: ReceiptTemplate[] = [
  // ================= RETAIL & GENERAL =================
  {
    id: 'general',
    name: 'General Retail',
    category: 'retail',
    keywords: ['general', 'store', 'shop', 'retail', 'pos', 'invoice', 'mart'],
    icon: Store,
    emoji: '🏪',
    accentColor: '#2563EB',
    tagline: 'Quality Products, Trusted Service',
    footerMessage: 'Thank you for your purchase!',
    billLabel: 'Invoice No',
    itemColumnLeft: 'Item x Qty',
    itemColumnRight: 'Rate',
    itemLabel: 'ITEMS',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Everyday Cotton Towel', quantity: 2, unitPrice: 199, total: 398, unit: 'Pc' },
      { productName: 'Storage Container Box', quantity: 1, unitPrice: 350, total: 350, unit: 'Pc' },
    ],
  },
  {
    id: 'grocery',
    name: 'Grocery / Supermarket',
    category: 'retail',
    keywords: ['grocery', 'supermarket', 'kirana', 'provisions', 'staples', 'grains', 'oil'],
    icon: ShoppingCart,
    emoji: '🛒',
    accentColor: '#15803D',
    tagline: 'Everyday Essentials At Best Prices',
    footerMessage: 'Thank you for shopping with us! Fresh stock daily.',
    billLabel: 'Invoice No',
    itemColumnLeft: 'Item x Qty',
    itemColumnRight: 'Rate',
    itemLabel: 'GROCERY ITEMS',
    showTaxBreakdown: true,
    showCustomerLine: false,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Basmati Rice Premium (5kg)', quantity: 1, unitPrice: 420, total: 420, unit: 'Bag' },
      { productName: 'Sunflower Cooking Oil 1L', quantity: 2, unitPrice: 145, total: 290, unit: 'Pouch' },
      { productName: 'Refined Sugar (1kg)', quantity: 3, unitPrice: 44, total: 132, unit: 'Kg' },
    ],
  },
  {
    id: 'fruits_vegetables',
    name: 'Fruits & Vegetables',
    category: 'retail',
    keywords: ['fruits', 'vegetables', 'sabzi', 'mandi', 'farm', 'fresh', 'organic', 'produce'],
    icon: Apple,
    emoji: '🥦',
    accentColor: '#16A34A',
    tagline: 'Farm Fresh Harvest Daily',
    footerMessage: 'Eat fresh, stay healthy! Visit again.',
    billLabel: 'Bill No',
    itemColumnLeft: 'Item (Kg/Gms)',
    itemColumnRight: 'Rate',
    itemLabel: 'FRESH PRODUCE',
    showTaxBreakdown: false,
    showCustomerLine: false,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Farm Fresh Tomatoes (Kg)', quantity: 2, unitPrice: 35, total: 70, unit: 'Kg' },
      { productName: 'Red Apples Shimla (Kg)', quantity: 1.5, unitPrice: 160, total: 240, unit: 'Kg' },
      { productName: 'Organic Spinach Bunch', quantity: 2, unitPrice: 20, total: 40, unit: 'Bunch' },
    ],
  },
  {
    id: 'meat_poultry',
    name: 'Meat & Fish Shop',
    category: 'retail',
    keywords: ['meat', 'chicken', 'fish', 'poultry', 'butcher', 'mutton', 'prawns', 'seafood'],
    icon: Fish,
    emoji: '🥩',
    accentColor: '#B91C1C',
    tagline: 'Freshly Cut & Hygienically Packed',
    footerMessage: 'Thank you! Always fresh & chilled.',
    billLabel: 'Bill No',
    itemColumnLeft: 'Cut / Item (Kg)',
    itemColumnRight: 'Amount',
    itemLabel: 'FRESH CUTS',
    showTaxBreakdown: false,
    showCustomerLine: false,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Curry Cut Chicken (Skinless)', quantity: 1, unitPrice: 240, total: 240, unit: 'Kg' },
      { productName: 'Fresh Surmai Fish Slices', quantity: 0.5, unitPrice: 700, total: 350, unit: 'Kg' },
    ],
  },
  {
    id: 'hardware',
    name: 'Hardware & Sanitary',
    category: 'retail',
    keywords: ['hardware', 'tools', 'paints', 'sanitary', 'plumbing', 'electrical', 'cement'],
    icon: Hammer,
    emoji: '🔨',
    accentColor: '#57534E',
    tagline: 'Tools, Paints & Building Supplies',
    footerMessage: 'Thank you for your business! Exchange on un-opened items.',
    billLabel: 'Bill No',
    itemColumnLeft: 'Item x Qty',
    itemColumnRight: 'Amount',
    itemLabel: 'HARDWARE ITEMS',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Asian Paints Primer 4L', quantity: 1, unitPrice: 620, total: 620, unit: 'Can' },
      { productName: 'SS Door Hinges 4-inch', quantity: 6, unitPrice: 85, total: 510, unit: 'Pcs' },
    ],
  },
  {
    id: 'bookstore',
    name: 'Bookstore & Stationery',
    category: 'retail',
    keywords: ['books', 'stationery', 'notebooks', 'pens', 'school', 'office', 'reading'],
    icon: BookOpen,
    emoji: '📚',
    accentColor: '#1D4ED8',
    tagline: 'Read. Write. Learn. Grow.',
    footerMessage: 'Thank you for your purchase — happy reading!',
    billLabel: 'Bill No',
    itemColumnLeft: 'Item x Qty',
    itemColumnRight: 'Amount',
    itemLabel: 'BOOKS & STATIONERY',
    showTaxBreakdown: false,
    showCustomerLine: false,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Hardbound Ruled Diary A5', quantity: 2, unitPrice: 180, total: 360, unit: 'Pc' },
      { productName: 'Parker Jotter Ball Pen', quantity: 1, unitPrice: 275, total: 275, unit: 'Pc' },
    ],
  },
  {
    id: 'paan_kiosk',
    name: 'Kiosk & Quick Convenience',
    category: 'retail',
    keywords: ['paan', 'tobacco', 'kiosk', 'snacks', 'soda', 'beverages', 'chips', 'confectionery'],
    icon: Sparkles,
    emoji: '🍃',
    accentColor: '#047857',
    tagline: 'Quick Refreshments & Daily Bites',
    footerMessage: 'Thanks for stopping by — visit again!',
    billLabel: 'Slip #',
    itemColumnLeft: 'Item x Qty',
    itemColumnRight: 'Amount',
    itemLabel: 'ITEMS',
    showTaxBreakdown: false,
    showCustomerLine: false,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Meetha Paan Special', quantity: 2, unitPrice: 35, total: 70, unit: 'Pc' },
      { productName: 'Cold Drink Can 300ml', quantity: 2, unitPrice: 40, total: 80, unit: 'Can' },
    ],
  },

  // ================= RESTAURANT & HOTEL (58mm) =================
  {
    id: 'restaurant',
    name: 'Fine Dining Restaurant',
    category: 'restaurant',
    keywords: ['restaurant', 'dining', 'food', 'table', 'kot', 'meal', 'lunch', 'dinner'],
    icon: UtensilsCrossed,
    emoji: '🍽️',
    accentColor: '#7C2D12',
    tagline: 'Fine Dining Experience',
    footerMessage: 'Thank you for dining with us. Visit again soon!',
    billLabel: 'Bill #',
    itemColumnLeft: 'Item x Qty',
    itemColumnRight: 'Rate',
    itemLabel: 'FOOD & BEVERAGES',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '=',
    sampleItems: [
      { productName: 'Paneer Butter Masala', quantity: 1, unitPrice: 320, total: 320, unit: 'Portion' },
      { productName: 'Butter Garlic Naan', quantity: 3, unitPrice: 55, total: 165, unit: 'Pc' },
      { productName: 'Jeera Rice Half', quantity: 1, unitPrice: 140, total: 140, unit: 'Plate' },
    ],
  },
  {
    id: 'restaurant_bill',
    name: 'Restaurant Bill',
    category: 'restaurant',
    keywords: ['restaurant bill', 'cash bill', 'diner', 'waiter', 'table', 'vat', 'service charge', 'local diners'],
    icon: UtensilsCrossed,
    emoji: '🍽️',
    accentColor: '#1E293B',
    tagline: 'CASH/BILL',
    footerMessage: 'Thank you for dining with us!',
    billLabel: 'Bill No',
    itemColumnLeft: 'Item',
    itemColumnRight: 'Total Rs',
    itemLabel: 'ORDER',
    showTaxBreakdown: false,
    showCustomerLine: false,
    dividerChar: '-',
    layout: 'restaurant_bill',
    paperFit: '48mm',
    previewStoreName: 'HOTEL BLUE MOON',
    previewAddress: 'MG ROAD, PUNE',
    previewPhone: '020-24441190',
    previewInvoice: '1842',
    previewDate: '25/08/26 13:42',
    previewTableNo: '12',
    previewWaiter: 'RAJ',
    sampleItems: [
      { productName: 'FLAVOURED MOJITO', quantity: 1, unitPrice: 330, total: 330 },
      { productName: 'CUCUMBER MINT', quantity: 1, unitPrice: 170, total: 170 },
      { productName: 'LONG ISLAND ELEC', quantity: 2, unitPrice: 340, total: 680 },
      { productName: 'CRUNCHY SALAD', quantity: 1, unitPrice: 160, total: 160 },
      { productName: 'ASSORTED SATAY', quantity: 1, unitPrice: 260, total: 260 },
      { productName: 'TEQUILA CHICKEN', quantity: 1, unitPrice: 320, total: 320 },
      { productName: 'FAJITAS CHICKEN', quantity: 1, unitPrice: 300, total: 300 },
      { productName: 'SURF N TURF', quantity: 1, unitPrice: 360, total: 360 },
    ],
  },
  {
    id: 'restaurant_compact',
    name: 'Compact Dine-In',
    category: 'restaurant',
    keywords: ['compact', 'dine in', 'table', '58mm', 'hotel', 'waiter', 'tno', 'short bill'],
    icon: Utensils,
    emoji: '🍽️',
    accentColor: '#0F172A',
    tagline: 'CASH/BILL',
    footerMessage: 'Thank you for dining with us!',
    billLabel: 'Bill',
    itemColumnLeft: 'ITEM',
    itemColumnRight: 'AMT',
    itemLabel: 'ORDER',
    showTaxBreakdown: true,
    showCustomerLine: false,
    dividerChar: '-',
    layout: 'restaurant_compact',
    paperFit: '48mm',
    previewStoreName: 'HOTEL BLUE MOON',
    previewAddress: 'MG ROAD, PUNE',
    previewPhone: '020-24441190',
    previewInvoice: '1842',
    previewDate: '25/08/26 13:42',
    previewTableNo: '12',
    previewWaiter: 'RAJ',
    sampleItems: [
      { productName: 'DAL FRY', quantity: 1, unitPrice: 180, total: 180 },
      { productName: 'BUTTER NAAN', quantity: 4, unitPrice: 55, total: 220 },
      { productName: 'JEERA RICE', quantity: 1, unitPrice: 140, total: 140 },
    ],
  },
  {
    id: 'restaurant_gst',
    name: 'GST Tax Invoice',
    category: 'restaurant',
    keywords: ['gst', 'tax invoice', 'cgst', 'sgst', 'registered', 'gstin', 'dine in'],
    icon: Receipt,
    emoji: '🧾',
    accentColor: '#14532D',
    tagline: 'TAX INVOICE',
    footerMessage: 'Thank you. Visit again.',
    billLabel: 'Bill',
    itemColumnLeft: 'ITEM',
    itemColumnRight: 'AMT',
    itemLabel: 'ORDER',
    showTaxBreakdown: true,
    showCustomerLine: false,
    dividerChar: '-',
    layout: 'restaurant_gst',
    paperFit: '48mm',
    previewStoreName: 'SPICE GARDEN',
    previewAddress: 'FC ROAD, PUNE',
    previewPhone: '020-25551212',
    previewGstin: '27AABCU9603R1ZM',
    previewInvoice: '2201',
    previewDate: '25/08/26 14:10',
    previewTableNo: '07',
    previewWaiter: 'ANITA',
    sampleItems: [
      { productName: 'PANEER TIKKA', quantity: 1, unitPrice: 280, total: 280 },
      { productName: 'DAL MAKHANI', quantity: 1, unitPrice: 240, total: 240 },
      { productName: 'GARLIC NAAN', quantity: 2, unitPrice: 55, total: 110 },
    ],
  },
  {
    id: 'restaurant_takeaway',
    name: 'Takeaway / Parcel',
    category: 'restaurant',
    keywords: ['takeaway', 'parcel', 'pickup', 'packed', 'counter', 'guest', 'to go'],
    icon: ShoppingBag,
    emoji: '🥡',
    accentColor: '#9A3412',
    tagline: 'PARCEL',
    footerMessage: 'Packed fresh. Enjoy!',
    billLabel: 'Bill',
    itemColumnLeft: 'Item',
    itemColumnRight: 'Total',
    itemLabel: 'PARCEL',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '-',
    layout: 'restaurant_takeaway',
    paperFit: '48mm',
    previewStoreName: 'TANDOORI EXPRESS',
    previewAddress: 'FC ROAD, PUNE',
    previewPhone: '020-24440011',
    previewInvoice: '903',
    previewDate: '25/08/26 13:05',
    previewCustomerName: 'PRIYA SHAH',
    previewCustomerPhone: '9876543210',
    sampleItems: [
      { productName: 'VEG BIRYANI', quantity: 1, unitPrice: 220, total: 220 },
      { productName: 'BOONDI RAITA', quantity: 1, unitPrice: 40, total: 40 },
    ],
  },
  {
    id: 'restaurant_dhaba',
    name: 'Dhaba / Family Diner',
    category: 'restaurant',
    keywords: ['dhaba', 'highway', 'family diner', 'roti', 'dal', 'lassi', 'unregistered', 'cash'],
    icon: Flame,
    emoji: '🔥',
    accentColor: '#B45309',
    tagline: 'CASH BILL',
    footerMessage: 'Visit again bhai!',
    billLabel: 'Bill',
    itemColumnLeft: 'ITEM',
    itemColumnRight: 'AMT',
    itemLabel: 'ORDER',
    showTaxBreakdown: false,
    showCustomerLine: false,
    dividerChar: '-',
    layout: 'restaurant_compact',
    paperFit: '48mm',
    previewStoreName: 'DHABA 24',
    previewAddress: 'NH48 HIGHWAY',
    previewPhone: '9822001122',
    previewInvoice: '77',
    previewDate: '25/08/26 12:40',
    previewTableNo: '4',
    previewWaiter: 'RAMU',
    sampleItems: [
      { productName: 'DAL TADKA', quantity: 1, unitPrice: 140, total: 140 },
      { productName: 'TAVA ROTI', quantity: 6, unitPrice: 15, total: 90 },
      { productName: 'LASSI', quantity: 2, unitPrice: 40, total: 80 },
    ],
  },
  {
    id: 'restaurant_bar',
    name: 'Bar & Lounge',
    category: 'restaurant',
    keywords: ['bar', 'lounge', 'drinks', 'cocktail', 'mojito', 'service charge', 'vat', 'nightlife'],
    icon: Wine,
    emoji: '🍸',
    accentColor: '#1E1B4B',
    tagline: 'CASH/BILL',
    footerMessage: 'Please drink responsibly.',
    billLabel: 'Bill',
    itemColumnLeft: 'Item',
    itemColumnRight: 'Total',
    itemLabel: 'BAR ORDER',
    showTaxBreakdown: false,
    showCustomerLine: false,
    dividerChar: '-',
    layout: 'restaurant_bill',
    paperFit: '48mm',
    previewStoreName: 'NIGHT OWL BAR',
    previewAddress: 'KOREGAON PARK',
    previewPhone: '020-26667890',
    previewInvoice: '3318',
    previewDate: '25/08/26 22:15',
    previewTableNo: '9',
    previewWaiter: 'VIKAS',
    sampleItems: [
      { productName: 'MOJITO', quantity: 2, unitPrice: 330, total: 660 },
      { productName: 'LONG ISLAND', quantity: 1, unitPrice: 340, total: 340 },
      { productName: 'CRUNCHY SALAD', quantity: 1, unitPrice: 160, total: 160 },
    ],
  },
  {
    id: 'restaurant_cloud',
    name: 'Cloud Kitchen',
    category: 'restaurant',
    keywords: ['cloud kitchen', 'delivery', 'dark kitchen', 'online', 'swiggy', 'zomato', 'packed'],
    icon: ChefHat,
    emoji: '📦',
    accentColor: '#0F766E',
    tagline: 'DELIVERY ORDER',
    footerMessage: 'Please check the seal.',
    billLabel: 'Order',
    itemColumnLeft: 'Item',
    itemColumnRight: 'Total',
    itemLabel: 'PACKED',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '-',
    layout: 'restaurant_takeaway',
    paperFit: '48mm',
    previewStoreName: 'BOXED BITES',
    previewAddress: 'KIRKEE, PUNE',
    previewPhone: '020-26660011',
    previewInvoice: '4418',
    previewDate: '25/08/26 20:18',
    previewCustomerName: 'AMIT K',
    previewCustomerPhone: '9811122233',
    sampleItems: [
      { productName: 'BUTTER CHKN BOWL', quantity: 1, unitPrice: 249, total: 249 },
      { productName: 'GARLIC NAAN PK', quantity: 2, unitPrice: 40, total: 80 },
    ],
  },
  {
    id: 'restaurant_roomservice',
    name: 'Room Service',
    category: 'restaurant',
    keywords: ['room service', 'hotel', 'in room', 'guest', 'steward', 'charge to room'],
    icon: BedDouble,
    emoji: '🛎️',
    accentColor: '#334155',
    tagline: 'ROOM SERVICE',
    footerMessage: 'Charge to room. Thank you.',
    billLabel: 'Bill',
    itemColumnLeft: 'ITEM',
    itemColumnRight: 'AMT',
    itemLabel: 'ORDER',
    showTaxBreakdown: true,
    showCustomerLine: false,
    dividerChar: '-',
    layout: 'restaurant_roomservice',
    paperFit: '48mm',
    previewStoreName: 'THE GRAND STAY',
    previewAddress: 'MG ROAD, PUNE',
    previewPhone: '020-26110000',
    previewInvoice: '118',
    previewDate: '25/08/26 21:05',
    previewTableNo: '304',
    previewWaiter: 'STEWARD',
    sampleItems: [
      { productName: 'CLUB SANDWICH', quantity: 1, unitPrice: 320, total: 320 },
      { productName: 'LIME SODA', quantity: 1, unitPrice: 90, total: 90 },
    ],
  },

  // ================= FOOD & DINING =================
  {
    id: 'cafe',
    name: 'Cafe & Coffee Bar',
    category: 'food',
    keywords: ['cafe', 'coffee', 'espresso', 'tea', 'latte', 'sandwich', 'beverages', 'bakery'],
    icon: Coffee,
    emoji: '☕',
    accentColor: '#78350F',
    tagline: 'Artisanal Coffee & Bakes',
    footerMessage: 'Thanks for the visit — enjoy your brew!',
    billLabel: 'Order No',
    itemColumnLeft: 'Item x Qty',
    itemColumnRight: 'Amount',
    itemLabel: 'CAFE ORDER',
    showTaxBreakdown: false,
    showCustomerLine: false,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Hazelnut Cappuccino (Large)', quantity: 1, unitPrice: 220, total: 220, unit: 'Cup' },
      { productName: 'Grilled Cheese Panini', quantity: 1, unitPrice: 195, total: 195, unit: 'Pc' },
      { productName: 'Warm Choco Brownie', quantity: 1, unitPrice: 140, total: 140, unit: 'Slice' },
    ],
  },
  {
    id: 'bakery',
    name: 'Bakery & Patisserie',
    category: 'food',
    keywords: ['bakery', 'cake', 'pastry', 'croissant', 'bread', 'cookies', 'patisserie', 'muffins'],
    icon: Croissant,
    emoji: '🥐',
    accentColor: '#B45309',
    tagline: 'Freshly Baked Everyday',
    footerMessage: 'Thank you for stopping by — fresh bakes daily!',
    billLabel: 'Bill No',
    itemColumnLeft: 'Item',
    itemColumnRight: 'Amount',
    itemLabel: 'BAKERY DELIGHTS',
    showTaxBreakdown: false,
    showCustomerLine: false,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Butter Croissant', quantity: 2, unitPrice: 85, total: 170, unit: 'Pc' },
      { productName: 'Belgian Chocolate Cake 0.5kg', quantity: 1, unitPrice: 450, total: 450, unit: 'Pc' },
    ],
  },
  {
    id: 'fast_food',
    name: 'Fast Food & QSR',
    category: 'food',
    keywords: ['fast food', 'qsr', 'burger', 'pizza', 'fries', 'chaat', 'roll', 'token', 'counter'],
    icon: Pizza,
    emoji: '🍔',
    accentColor: '#EA580C',
    tagline: 'Hot, Crispy & Delicious',
    footerMessage: 'Please present token at the counter for pickup.',
    billLabel: 'Token #',
    itemColumnLeft: 'Item x Qty',
    itemColumnRight: 'Amount',
    itemLabel: 'ORDER ITEMS',
    showTaxBreakdown: false,
    showCustomerLine: false,
    dividerChar: '=',
    sampleItems: [
      { productName: 'Crispy Veg Whopper Meal', quantity: 1, unitPrice: 249, total: 249, unit: 'Meal' },
      { productName: 'Peri Peri French Fries (L)', quantity: 1, unitPrice: 119, total: 119, unit: 'Box' },
    ],
  },
  {
    id: 'sweet_shop',
    name: 'Mithai & Sweet Mart',
    category: 'food',
    keywords: ['sweets', 'mithai', 'namkeen', 'dairy', 'ladoo', 'kaju katli', 'peda', 'samosa'],
    icon: IceCream,
    emoji: '🍨',
    accentColor: '#D97706',
    tagline: 'Pure Ghee Sweets & Savouries',
    footerMessage: 'Celebrating sweetness with you! Visit again.',
    billLabel: 'Bill No',
    itemColumnLeft: 'Mithai / Weight',
    itemColumnRight: 'Amount',
    itemLabel: 'SWEETS & SAVOURIES',
    showTaxBreakdown: false,
    showCustomerLine: false,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Kaju Katli Special (500g)', quantity: 1, unitPrice: 480, total: 480, unit: 'Box' },
      { productName: 'Motichoor Ladoo (500g)', quantity: 1, unitPrice: 260, total: 260, unit: 'Box' },
      { productName: 'Special Masala Namkeen', quantity: 2, unitPrice: 90, total: 180, unit: 'Pouch' },
    ],
  },
  {
    id: 'beverage',
    name: 'Juice Bar & Chai Point',
    category: 'food',
    keywords: ['juice', 'chai', 'tea', 'shake', 'smoothie', 'beverage', 'lassi', 'tapri'],
    icon: CupSoda,
    emoji: '🥤',
    accentColor: '#0284C7',
    tagline: 'Freshly Squeezed & Brewed To Perfection',
    footerMessage: 'Stay refreshed! See you again soon.',
    billLabel: 'Token No',
    itemColumnLeft: 'Drink x Qty',
    itemColumnRight: 'Amount',
    itemLabel: 'BEVERAGES',
    showTaxBreakdown: false,
    showCustomerLine: false,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Fresh Mosambi Juice', quantity: 2, unitPrice: 60, total: 120, unit: 'Glass' },
      { productName: 'Adrak Elaichi Kadak Chai', quantity: 3, unitPrice: 20, total: 60, unit: 'Cup' },
    ],
  },

  // ================= FASHION & LIFESTYLE =================
  {
    id: 'fashion',
    name: 'Fashion & Apparel',
    category: 'fashion',
    keywords: ['fashion', 'apparel', 'clothing', 'garments', 'shirts', 'jeans', 'boutique', 'dresses'],
    icon: Shirt,
    emoji: '👕',
    accentColor: '#DB2777',
    tagline: 'Trends That Define Your Style',
    footerMessage: 'Thank you for shopping! Exchange allowed within 7 days with bill.',
    billLabel: 'Invoice No',
    itemColumnLeft: 'Garment',
    itemColumnRight: 'Amount',
    itemLabel: 'APPAREL & ACCESSORIES',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Slim Fit Cotton Shirt (L)', quantity: 1, unitPrice: 1299, total: 1299, unit: 'Pc' },
      { productName: 'Stretch Denim Jeans (32)', quantity: 1, unitPrice: 1899, total: 1899, unit: 'Pc' },
    ],
  },
  {
    id: 'footwear',
    name: 'Footwear & Shoe Store',
    category: 'fashion',
    keywords: ['footwear', 'shoes', 'sandals', 'sneakers', 'boots', 'slippers', 'leather'],
    icon: Footprints,
    emoji: '👟',
    accentColor: '#4338CA',
    tagline: 'Step Out In Comfort & Style',
    footerMessage: 'Walk in comfort! Exchange within 7 days with tag intact.',
    billLabel: 'Bill No',
    itemColumnLeft: 'Model / Size',
    itemColumnRight: 'Amount',
    itemLabel: 'FOOTWEAR',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Air Cushion Running Shoes (UK 9)', quantity: 1, unitPrice: 2499, total: 2499, unit: 'Pair' },
      { productName: 'Leather Formal Slip-on (UK 9)', quantity: 1, unitPrice: 1850, total: 1850, unit: 'Pair' },
    ],
  },
  {
    id: 'jewellery',
    name: 'Jewellery & Gold Store',
    category: 'fashion',
    keywords: ['jewellery', 'gold', 'silver', 'diamond', 'necklace', 'rings', 'hallmark', 'ornaments'],
    icon: Gem,
    emoji: '💎',
    accentColor: '#A16207',
    tagline: 'Timeless Purity & Hallmark Elegance',
    footerMessage: 'Thank you! Hallmarked authenticity certificate enclosed.',
    billLabel: 'Tax Invoice',
    itemColumnLeft: 'Ornament / Wt (g)',
    itemColumnRight: 'Amount',
    itemLabel: 'JEWELLERY ITEMS',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '=',
    sampleItems: [
      { productName: '22K Gold Ring (3.45g)', quantity: 1, unitPrice: 24800, total: 24800, unit: 'Pc' },
      { productName: 'Silver Anklet Pair 925 (45g)', quantity: 1, unitPrice: 3800, total: 3800, unit: 'Pair' },
    ],
  },
  {
    id: 'furniture',
    name: 'Furniture & Home Decor',
    category: 'fashion',
    keywords: ['furniture', 'sofa', 'decor', 'table', 'chair', 'bed', 'mattress', 'interior'],
    icon: Sofa,
    emoji: '🛋️',
    accentColor: '#92400E',
    tagline: 'Furnishing Comfort & Modern Spaces',
    footerMessage: 'Thank you! Delivery & assembly scheduled as discussed.',
    billLabel: 'Invoice No',
    itemColumnLeft: 'Item / Model',
    itemColumnRight: 'Amount',
    itemLabel: 'FURNITURE ITEMS',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Ergonomic Mesh Office Chair', quantity: 1, unitPrice: 6500, total: 6500, unit: 'Pc' },
      { productName: 'Sheesham Wood Side Table', quantity: 2, unitPrice: 2200, total: 4400, unit: 'Pc' },
    ],
  },
  {
    id: 'gift_toys',
    name: 'Gifts, Toys & Novelties',
    category: 'fashion',
    keywords: ['gifts', 'toys', 'novelties', 'party', 'birthday', 'games', 'cards', 'souvenirs'],
    icon: Gift,
    emoji: '🎁',
    accentColor: '#BE185D',
    tagline: 'Gifts & Toys For Every Celebration',
    footerMessage: 'Thank you for spreading smiles! Gift wrapping available.',
    billLabel: 'Gift Slip No',
    itemColumnLeft: 'Item x Qty',
    itemColumnRight: 'Amount',
    itemLabel: 'GIFT & TOY ITEMS',
    showTaxBreakdown: true,
    showCustomerLine: false,
    dividerChar: '-',
    sampleItems: [
      { productName: 'RC Racing Drift Car (1:16)', quantity: 1, unitPrice: 1250, total: 1250, unit: 'Pc' },
      { productName: 'Ceramic Designer Mug Set', quantity: 1, unitPrice: 499, total: 499, unit: 'Set' },
    ],
  },

  // ================= ELECTRONICS & TECH =================
  {
    id: 'electronics',
    name: 'Electronics & Appliances',
    category: 'tech',
    keywords: ['electronics', 'appliances', 'tv', 'ac', 'fridge', 'speaker', 'home audio'],
    icon: Cpu,
    emoji: '💻',
    accentColor: '#0F172A',
    tagline: 'Genuine Products, Brand Warranties',
    footerMessage: 'Thank you! Manufacturer warranty card valid with this invoice.',
    billLabel: 'Invoice No',
    itemColumnLeft: 'Product / Model',
    itemColumnRight: 'Amount',
    itemLabel: 'ELECTRONICS & APPLIANCES',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '=',
    sampleItems: [
      { productName: 'Smart LED TV 43-inch 4K', quantity: 1, unitPrice: 23999, total: 23999, unit: 'Unit' },
      { productName: 'Wireless Bluetooth Soundbar 120W', quantity: 1, unitPrice: 4499, total: 4499, unit: 'Unit' },
    ],
  },
  {
    id: 'mobile',
    name: 'Mobile & Accessories',
    category: 'tech',
    keywords: ['mobile', 'smartphone', 'cases', 'chargers', 'earbuds', 'tempered', 'gadgets'],
    icon: Smartphone,
    emoji: '📱',
    accentColor: '#0369A1',
    tagline: 'Latest Smartphones & Premium Accessories',
    footerMessage: 'Thank you! Please keep this bill safe for warranty claims.',
    billLabel: 'Tax Invoice',
    itemColumnLeft: 'Item / IMEI',
    itemColumnRight: 'Amount',
    itemLabel: 'SMART DEVICES & ACCESSORIES',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '=',
    sampleItems: [
      { productName: '5G Smartphone 8GB/128GB', quantity: 1, unitPrice: 17999, total: 17999, unit: 'Device' },
      { productName: '65W Fast GaN Charger Type-C', quantity: 1, unitPrice: 1299, total: 1299, unit: 'Pc' },
    ],
  },
  {
    id: 'device_repair',
    name: 'Mobile & Laptop Repair Service',
    category: 'tech',
    keywords: ['repair', 'laptop service', 'screen replacement', 'battery', 'chip level', 'job card'],
    icon: Wrench,
    emoji: '🔧',
    accentColor: '#334155',
    tagline: 'Expert Screen, Battery & Board Repairs',
    footerMessage: '30-day testing warranty on replaced hardware spare parts.',
    billLabel: 'Job Card #',
    itemColumnLeft: 'Service / Part',
    itemColumnRight: 'Amount',
    itemLabel: 'REPAIR & SERVICE',
    showTaxBreakdown: false,
    showCustomerLine: true,
    dividerChar: '=',
    sampleItems: [
      { productName: 'OLED Display Screen Assembly', quantity: 1, unitPrice: 2800, total: 2800, unit: 'Part' },
      { productName: 'Internal Battery Replacement', quantity: 1, unitPrice: 1200, total: 1200, unit: 'Part' },
      { productName: 'Service & Diagnostic Labor', quantity: 1, unitPrice: 350, total: 350, unit: 'Labor' },
    ],
  },

  // ================= SERVICES & REPAIR =================
  {
    id: 'salon',
    name: 'Salon, Spa & Beauty Care',
    category: 'services',
    keywords: ['salon', 'spa', 'haircut', 'facial', 'massage', 'makeup', 'parlour', 'grooming'],
    icon: Scissors,
    emoji: '✂️',
    accentColor: '#BE185D',
    tagline: 'Glow With Elegance & Personal Care',
    footerMessage: 'Thank you for pampering yourself! Book your next appointment soon.',
    billLabel: 'Bill No',
    itemColumnLeft: 'Service',
    itemColumnRight: 'Amount',
    itemLabel: 'SALON SERVICES',
    showTaxBreakdown: false,
    showCustomerLine: true,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Premium Haircut & Beard Styling', quantity: 1, unitPrice: 350, total: 350, unit: 'Svc' },
      { productName: 'Organic Fruit Facial & Glow Pack', quantity: 1, unitPrice: 850, total: 850, unit: 'Svc' },
    ],
  },
  {
    id: 'garage',
    name: 'Auto Garage & Car Workshop',
    category: 'services',
    keywords: ['garage', 'car service', 'bike repair', 'engine oil', 'mechanic', 'tyres', 'puncture'],
    icon: Car,
    emoji: '🚗',
    accentColor: '#B91C1C',
    tagline: 'Reliable Auto Repairs & Genuine Spares',
    footerMessage: 'Thank you! Drive safe — next scheduled service in 5,000 KM.',
    billLabel: 'Job Sheet #',
    itemColumnLeft: 'Service / Spare Part',
    itemColumnRight: 'Amount',
    itemLabel: 'VEHICLE SERVICE & PARTS',
    showTaxBreakdown: false,
    showCustomerLine: true,
    dividerChar: '=',
    sampleItems: [
      { productName: 'Synthetic Engine Oil 5W30 (3.5L)', quantity: 1, unitPrice: 1650, total: 1650, unit: 'Can' },
      { productName: 'Oil Filter & Air Filter Kit', quantity: 1, unitPrice: 420, total: 420, unit: 'Set' },
      { productName: 'General Periodic Maintenance Labor', quantity: 1, unitPrice: 650, total: 650, unit: 'Labor' },
    ],
  },
  {
    id: 'car_wash',
    name: 'Car Wash & Auto Detailing',
    category: 'services',
    keywords: ['car wash', 'detailing', 'foam wash', 'ceramic polish', 'interior dry clean'],
    icon: Droplets,
    emoji: '🧼',
    accentColor: '#0284C7',
    tagline: 'Foam Wash, Steam Clean & Polish',
    footerMessage: 'Shine on the road! Thank you for trusting us.',
    billLabel: 'Job Slip #',
    itemColumnLeft: 'Wash Package',
    itemColumnRight: 'Amount',
    itemLabel: 'DETAILING SERVICES',
    showTaxBreakdown: false,
    showCustomerLine: true,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Full High Pressure Foam Wash', quantity: 1, unitPrice: 450, total: 450, unit: 'Svc' },
      { productName: 'Interior Vacuum & Dashboard Polish', quantity: 1, unitPrice: 350, total: 350, unit: 'Svc' },
    ],
  },
  {
    id: 'laundry',
    name: 'Laundry & Dry Cleaning',
    category: 'services',
    keywords: ['laundry', 'dry clean', 'ironing', 'wash', 'steam press', 'quilts', 'curtains'],
    icon: Flame,
    emoji: '🧺',
    accentColor: '#0284C7',
    tagline: 'Express Wash, Steam Press & Care',
    footerMessage: 'Please present this pickup slip at delivery counter.',
    billLabel: 'Pickup Token #',
    itemColumnLeft: 'Garment x Pcs',
    itemColumnRight: 'Amount',
    itemLabel: 'LAUNDRY ITEMS',
    showTaxBreakdown: false,
    showCustomerLine: true,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Shirt / Trouser Steam Press', quantity: 5, unitPrice: 20, total: 100, unit: 'Pcs' },
      { productName: 'Blazer Suit Premium Dry Clean', quantity: 1, unitPrice: 350, total: 350, unit: 'Set' },
      { productName: 'Double Bed Blanket Wash', quantity: 1, unitPrice: 250, total: 250, unit: 'Pc' },
    ],
  },
  {
    id: 'tailor',
    name: 'Tailoring & Boutique Studio',
    category: 'services',
    keywords: ['tailor', 'stitching', 'alteration', 'boutique', 'suit stitching', 'blouse', 'kurta'],
    icon: Scissors,
    emoji: '🪡',
    accentColor: '#7C3AED',
    tagline: 'Custom Tailoring & Made-To-Measure Fit',
    footerMessage: 'Trial fitting date confirmed. Please retain slip for collection.',
    billLabel: 'Trial Order #',
    itemColumnLeft: 'Pattern / Stitching',
    itemColumnRight: 'Amount',
    itemLabel: 'TAILORING ORDERS',
    showTaxBreakdown: false,
    showCustomerLine: true,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Designer Blouse Stitching with Lining', quantity: 1, unitPrice: 650, total: 650, unit: 'Pc' },
      { productName: 'Kurta Pyjama Stitching', quantity: 1, unitPrice: 500, total: 500, unit: 'Set' },
    ],
  },
  {
    id: 'courier_logistics',
    name: 'Courier & Parcel Booking',
    category: 'services',
    keywords: ['courier', 'parcel', 'logistics', 'tracking', 'cargo', 'delivery', 'consignment'],
    icon: Truck,
    emoji: '🚚',
    accentColor: '#D97706',
    tagline: 'Fast, Tracked Domestic & Express Cargo',
    footerMessage: 'Track your parcel online using the consignment number above.',
    billLabel: 'AWB / Tracking #',
    itemColumnLeft: 'Destination / Weight',
    itemColumnRight: 'Freight',
    itemLabel: 'CONSIGNMENT DETAILS',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '=',
    sampleItems: [
      { productName: 'Express Document Courier (Mumbai)', quantity: 1, unitPrice: 120, total: 120, unit: 'Doc' },
      { productName: 'Domestic Air Parcel (2.5 Kg)', quantity: 1, unitPrice: 380, total: 380, unit: 'Parcel' },
    ],
  },

  // ================= HEALTH & WELLNESS =================
  {
    id: 'pharmacy',
    name: 'Pharmacy & Medical Store',
    category: 'health',
    keywords: ['pharmacy', 'chemist', 'medical', 'medicines', 'doctor', 'tablets', 'syrup', 'drugs'],
    icon: Pill,
    emoji: '💊',
    accentColor: '#DC2626',
    tagline: 'Your Health & Well-being First',
    footerMessage: 'Get well soon! Please take medicines as directed by physician.',
    billLabel: 'Bill No',
    itemColumnLeft: 'Medicine / Batch',
    itemColumnRight: 'Amount',
    itemLabel: 'MEDICINES & PHARMA',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Paracetamol 650mg (Strip of 15)', quantity: 2, unitPrice: 32, total: 64, unit: 'Strip' },
      { productName: 'Multivitamin & Zinc Capsules (30)', quantity: 1, unitPrice: 285, total: 285, unit: 'Bottle' },
      { productName: 'Antiseptic Liquid 200ml', quantity: 1, unitPrice: 95, total: 95, unit: 'Bottle' },
    ],
  },
  {
    id: 'pathology_lab',
    name: 'Diagnostic Lab & Pathology',
    category: 'health',
    keywords: ['lab', 'pathology', 'blood test', 'diagnostic', 'clinic', 'health checkup', 'xray'],
    icon: Microscope,
    emoji: '🔬',
    accentColor: '#059669',
    tagline: 'Certified Clinical Diagnostic Reports',
    footerMessage: 'Reports will be ready online & on WhatsApp in 24 hours.',
    billLabel: 'Lab Ref #',
    itemColumnLeft: 'Investigation / Test',
    itemColumnRight: 'Amount',
    itemLabel: 'DIAGNOSTIC INVESTIGATIONS',
    showTaxBreakdown: false,
    showCustomerLine: true,
    dividerChar: '=',
    sampleItems: [
      { productName: 'Complete Blood Count (CBC)', quantity: 1, unitPrice: 350, total: 350, unit: 'Test' },
      { productName: 'Lipid Profile & Liver Panel (LFT)', quantity: 1, unitPrice: 850, total: 850, unit: 'Panel' },
    ],
  },
  {
    id: 'fitness_gym',
    name: 'Gym, Fitness & Supplements',
    category: 'health',
    keywords: ['gym', 'fitness', 'workout', 'membership', 'protein', 'supplements', 'yoga'],
    icon: Dumbbell,
    emoji: '🏋️',
    accentColor: '#7C2D12',
    tagline: 'Train Hard, Stay Fit, Live Healthy',
    footerMessage: 'Welcome to the fitness club! Carry your workout towel & shoes.',
    billLabel: 'Membership Slip',
    itemColumnLeft: 'Plan / Supplement',
    itemColumnRight: 'Amount',
    itemLabel: 'MEMBERSHIPS & NUTRITION',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '=',
    sampleItems: [
      { productName: 'Quarterly Gym Membership (3 Mo)', quantity: 1, unitPrice: 3500, total: 3500, unit: 'Sub' },
      { productName: 'Whey Protein Isolate 1Kg (Choco)', quantity: 1, unitPrice: 2200, total: 2200, unit: 'Tub' },
    ],
  },

  // ================= WHOLESALE & B2B =================
  {
    id: 'wholesale',
    name: 'B2B Wholesale & Bulk Supply',
    category: 'b2b',
    keywords: ['wholesale', 'b2b', 'bulk', 'distribution', 'trader', 'tax invoice', 'hsn', 'gst'],
    icon: Boxes,
    emoji: '📦',
    accentColor: '#1E293B',
    tagline: 'Authorized Wholesale Supply & Trade',
    footerMessage: 'Thank you for your bulk order! Goods received in sound condition.',
    billLabel: 'Tax Invoice No',
    itemColumnLeft: 'Item / HSN Code',
    itemColumnRight: 'Rate (Net)',
    itemLabel: 'WHOLESALE CONSIGNMENT',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '=',
    sampleItems: [
      { productName: 'Cotton Fabric Rolls (HSN 5208)', quantity: 10, unitPrice: 1450, total: 14500, unit: 'Roll' },
      { productName: 'Industrial Sewing Thread Boxes', quantity: 25, unitPrice: 180, total: 4500, unit: 'Box' },
    ],
  },
  {
    id: 'optician',
    name: 'Optician & Eyewear Studio',
    category: 'b2b',
    keywords: ['optician', 'eyewear', 'glasses', 'spectacles', 'lenses', 'sunglasses', 'frames'],
    icon: Glasses,
    emoji: '👓',
    accentColor: '#0284C7',
    tagline: 'Precision Vision & Designer Frames',
    footerMessage: 'Thank you! 1-year warranty on anti-glare lens coating.',
    billLabel: 'Rx Invoice No',
    itemColumnLeft: 'Frame / Lens Rx',
    itemColumnRight: 'Amount',
    itemLabel: 'EYEWEAR & PRESCRIPTION',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Titanium Lightweight Frame (Matte)', quantity: 1, unitPrice: 1800, total: 1800, unit: 'Pc' },
      { productName: 'Anti-Glare Blue Cut Lenses (Pair)', quantity: 1, unitPrice: 1400, total: 1400, unit: 'Pair' },
    ],
  },
  {
    id: 'cosmetics',
    name: 'Cosmetics & Beauty Supply',
    category: 'b2b',
    keywords: ['cosmetics', 'beauty', 'makeup', 'skincare', 'perfume', 'lipstick', 'serum'],
    icon: Sparkles,
    emoji: '💄',
    accentColor: '#BE185D',
    tagline: 'Luxury Skincare & Glam Essentials',
    footerMessage: 'Thank you for shopping! 100% genuine brand warranty.',
    billLabel: 'Invoice No',
    itemColumnLeft: 'Brand / Cosmetic',
    itemColumnRight: 'Amount',
    itemLabel: 'BEAUTY PRODUCTS',
    showTaxBreakdown: true,
    showCustomerLine: true,
    dividerChar: '-',
    sampleItems: [
      { productName: 'Matte Liquid Lipstick (Ruby Red)', quantity: 2, unitPrice: 499, total: 998, unit: 'Pc' },
      { productName: 'Vitamin C Brightening Serum 30ml', quantity: 1, unitPrice: 750, total: 750, unit: 'Bottle' },
    ],
  },
];

export const DEFAULT_TEMPLATE_ID = RECEIPT_TEMPLATES[0].id;

export function getTemplateById(id?: string | null): ReceiptTemplate {
  return RECEIPT_TEMPLATES.find((t) => t.id === id) || RECEIPT_TEMPLATES[0];
}
